dist: trusty
sudo: false

addons:
  ssh_known_hosts:
  - raw.threestrangedays.net

jobs:
  include:
  - stage: Build and Deploy
    env:
    - REL=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    script:
    - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.20.7/hugo_0.20.7_Linux-64bit.tar.gz
    - mkdir ./hugo
    - tar xf hugo_0.20.7_Linux-64bit.tar.gz -C ./hugo
    - "./hugo/hugo -d releases/$REL"
    deploy:
      provider: script
      skip_cleanup: true
      script: "./deployment/deploy.sh"
      on:
        branch: master

before_deploy:
- openssl aes-256-cbc -K $encrypted_88ffbfa01104_key -iv $encrypted_88ffbfa01104_iv
  -in ./deployment/deploy_ecdsa.enc -out /tmp/deploy_ecdsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_ecdsa
- ssh-add /tmp/deploy_ecdsa
