baseurl = "https://terinstock.com"
disablePathToLower = true
languageCode = "en-us"
title = "Terin Stock"
theme = "ts"

PygmentsCodeFences = true
pygmentsstyle = "perldoc"

footnoteReturnLinkContents = "↩"

SectionPagesMenu = "main"

[permalinks]
  post = "/:section/:year/:month/:slug"
  letter = "/:section/:year/:month/:slug"
  talk = "/:section/:year/:month/:slug"

[[menu.index]]
  name = "Blog Posts"
  weight = -130
  identifier = "post"
  url = "/post/"
[[menu.index]]
  name = "Talks"
  weight = -120
  identifier = "talk"
  url = "/talk/"
[[menu.index]]
  name = "Letters"
  weight = -110
  identifier = "letter"
  url = "/letter/"

[social]
  twitter = "terinjokes"
