baseurl = "https://terinstock.com"
title = "Terin Stock"
copyright = "© 2022 Terin Stock"
canonifyurls = true
languageCode = "en-us"
theme = "hugo-dusk"

disablePathToLower = true
footnoteReturnLinkContents = "↩"

[author]
  name = "Terin Stock"
  email = "terin@terinstock.com"

[markup.goldmark]
  autoHeadingIDType = "blackfriday"

[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  noClasses = true
  style = "rrt"

[permalinks]
  post = "/:section/:year/:month/:slug"
  talk = "/:section/:year/:month/:slug"

[[menu.main]]
  name = "Posts"
  weight = 1
  identifier = "post"
  url = "/post/"
[[menu.main]]
  name = "Talks"
  weight = 2
  identifier = "talk"
  url = "/talk/"

[params.meta]
  keywords = "blog, tech"

[params]
  github = "terinjokes"
  twitter = "terinjokes"
  linkedin = "terin"

[privacy]
  [privacy.youtube]
    privacyEnhanced = true
  [privacy.twitter]
    enableDNT = true
