name: publish
on:
  push:
    branches:
      - trunk
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.131.0"
          extended: true
      - run: hugo --minify
      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: "0b1bb2d40bbc1c8a1c6440bb1d756a3c"
          projectName: terin
          directory: public
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: "3"
