name: publish
on:
  push:
    branches:
      - trunk
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.147.9"
          extended: true
      - run: hugo --minify
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: "0b1bb2d40bbc1c8a1c6440bb1d756a3c"
          command: pages deploy public --project-name=terin
          githubToken: ${{ secrets.GITHUB_TOKEN }}
